name: Build web
on:
  workflow_dispatch:


jobs:
  build_web:
    runs-on: ubuntu-20.04


    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: cd web && npm install && npm run build && echo "Test works"
      
