name: Build Zinc
on: [push]


jobs:
  build_web:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-20.04, macos-11, windows-2022]
            node-version: [16]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd web && npm install && npm run build

      - name: Cache web/dist folder
        uses: actions/cache@v2
        with:
          path: web/dist
          key: ${{ runner.os }}-${{ env.GITHUB_SHA }}-web-dist
  # build_zinc:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #       matrix:
  #           os: [ubuntu-20.04, macos-11, windows-2022]
